// consultations.ts
export const consultations = [
    'Masculino',
    'Feminino',
    'Abdomen',
    'Cabeça e Pescoço',
    'Muscular',
    'Doppler',
    'Superfície',
    'Outros',
];

export const optionsMap = {
    Masculino: [
        { title: 'Axila', options: 'Inclui Doppler e Nódulo' },
        { title: 'Escrotal', options: '' },
        { title: 'Mamas', options: 'Inclui Linfonodos e Nódulo' },
        { title: 'Pelvis', options: 'Inclui Pediátrica' },
        { title: 'Prostata', options: 'Avaliação da saúde da próstata.' },
        { title: 'Transretal', options: 'Avaliação da saúde dos rins' },
    ],
    Feminino: [
        { title: 'Axila', options: 'Inclui doppler.' },
        { title: 'Diu', options: 'Detalhes aqui' },
        { title: 'Mamas', options: 'Inclui doppler.' },
        { title: 'Morfologicas', options: 'Inclui gemelar, trigemelar, com doppler e uterinas.' },
        { title: 'Obstetrica', options: 'Inclui trigemelar, inicial, com doppler, e todas as combinações' },
        { title: 'Transvarginal', options: 'Inclui seriada, pós histerectomia, avaliação cólo, musa IETA FIGO, contagem de folículos e com doppler. ' },
        { title: 'Pelvis', options: 'Inclui seriada e com doppler' },
        { title: 'Transsonografia', options: 'Inclui morfológica, gemelar e com doppler' },
    ],
    Abdomen: [
        { title: 'Parede', options: '' },
        { title: 'Superior', options: '' },
        { title: 'Total', options: 'Inclui pediátrico e novo' },
        { title: 'RimEnxertado', options: 'Inclui doppler' },
        { title: 'Hipocondrio', options: 'Inclui esquerdo/direito' },
        { title: 'FigadoViaBilares', options: 'Inclui doppler de veia porta' },
        { title: 'FID', options: '' },
        { title: 'AparelhoUrinario', options: 'Inclui pediátrico e doppler' },
        { title: 'RegiaoSacrococigea', options: '' },
    ],
    'Cabeça e Pescoço': [
        { title: 'Facial', options: 'Inclui lateral esquerda/direita'},
        { title: 'Tireoide', options: '' },
        { title: 'Cervical', options: 'Inclui tireóide, posterior e com doppler' },
        { title: 'CouroCabeludo', options: '' },
        { title: 'Glandulas', options: 'Inclui Salivares, Parótidas, Submandibulares e Submandibulares e Sublinguais'},
        { title: 'LateralPescoco', options: '' },
        { title: 'RegiaoParietal', options: '' },
        { title: 'RegiaoAuricularSubmentoniana', options: 'Inclui Periauricular, Retroauricular & Submentoniana' },
        { title: 'Transfontanelear', options: '' },
    ],
    Muscular: [
        { title: 'Gluteos', options: '' },
        { title: 'Coxa', options: 'Inclui esquerdo/direito e botinha' },
        { title: 'Panturrilha', options: 'Inclui doppler' },
        { title: 'Pe', options: 'Inclui doppler e botinha' },
        { title: 'Perna', options: 'Inclui botinha'},
        { title: 'Punho', options: 'Inclui doppler'},
        { title: 'Tornozelo', options: 'Inclui botinha'},
        { title: 'TendaoAquiles', options: ''},
        { title: 'Quadril', options: 'Inclui RN'},
        { title: 'Ombro', options: 'Inclui doppler'},
        { title: 'Mao', options: 'Inclui doppler e botinha'},
        { title: 'Joelho', options: 'Inclui doppler'},
        { title: 'Cotovelo', options: 'Inclui botinha'},
        { title: 'BracoAntebraco', options: 'Inclui Antebraco, doppler e botinha'},
        { title: 'Calcaneo', options: ''},
        { title: 'Dedo', options: 'Inclui polegar esquerdo/direito'},
        { title: 'FossaPoplitea', options: ''},
        { title: 'Deltoide', options: ''},
        { title: 'BursasTrocantericas', options: ''},
        { title: 'MusculaturaAbdominal', options: ''},
        { title: 'TerceiroPododaclito', options: 'Inclui esquerdo/direito'},
    ],
    Doppler: [
        { title: 'Ultrassom Doppler', options: 'Avaliação do fluxo sanguíneo em veias e artérias.' },
        { title: 'Doppler Colorido', options: 'Exame que utiliza cores para visualizar o fluxo sanguíneo.' },
    ],
    Superfície: [
        { title: 'Ultrassom Facial', options: '' },
        { title: 'Ultrassom Corporal', options: '' },
    ],
    Outros: [
        { title: 'Consulta Geral', options: 'Avaliação médica completa com orientações.' },
    ],
};
