// consultations.ts
export const consultations = [
    'Masculino',
    'Feminino',
    'Abdomen',
    'Cabeça e Pescoço',
    'Muscular',
    'Doppler',
    'Superfície',
    'Outros',
];

export const optionsMap = {
    Masculino: [
        { title: 'Axila', options: 'Detalhes aqui' },
        { title: 'Bolsa escrotal', options: 'Orientações sobre ultrassom escrotal' },
        { title: 'Mamas', options: 'Exame da mama' },
        { title: 'Pélvis', options: 'Deve incluir pediátrica' },
        { title: 'Próstata', options: 'Avaliação da saúde da próstata.' },
        { title: 'Transretal', options: 'Avaliação da saúde dos rins' },
    ],
    Feminino: [
        { title: 'Axila', options: 'Deve incluir doppler.' },
        { title: 'Diu', options: 'Detalhes aqui' },
        { title: 'Mamas', options: 'Deve incluir doppler.' },
        { title: 'Morfológicas', options: 'Deve incluir gemelar, trigemelar, com doppler e uterinas.' },
        { title: 'Obstétricas', options: 'Deve incluir trigemelar, inicial, com doppler, e todas as combinações' },
        { title: 'Transvarginal', options: 'Deve incluir seriada, pós histerectomia, avaliação cólo, musa IETA FIGO, contagem de folículos e com doppler. ' },
        { title: 'Pélvis', options: 'Deve incluir seriada e com doppler' },
        { title: 'Transsonografia', options: 'Deve incluir morfológica, gemelar e com doppler' },
    ],
    Abdomen: [
        { title: 'Parede Abdominal', options: '' },
        { title: 'Abdomen Superior', options: '' },
        { title: 'Abdomen Total', options: 'Deve incluir pediátrico e novo' },
        { title: 'Rim enxertado', options: 'Deve incluir doppler' },
        { title: 'Hipocôndrio', options: 'Deve incluir esquerdo/direito' },
        { title: 'Fígado e vias biliares', options: 'Deve incluir doppler de veia porta' },
        { title: 'FID', options: '' },
        { title: 'Aparelho Urinário', options: 'Deve incluir pediátrico e doppler' },
        { title: 'Região Sacrococcigea', options: '' },
    ],
    'Cabeça e Pescoço': [
        { title: 'Facial', options: 'Deve incluir lateral esquerda/direita'},
        { title: 'Tireóide', options: '' },
        { title: 'Cervical', options: 'Deve incluir tireóide, posterior e com doppler' },
        { title: 'Couro Cabeludo', options: '' },
        { title: 'Glândulas Salivares', options: '' },
        { title: 'Glândulas Parótidas', options: '' },
        { title: 'Glândulas Submandibulares', options: '' },
        { title: 'Glândulas Submandibulares e Sublinguais', options: '' },
        { title: 'Parótidas', options: '' },
        { title: 'Lateral do Pescoço', options: '' },
        { title: 'Região Parietal', options: '' },
        { title: 'Região Periauricular', options: '' },
        { title: 'Região Retroauricular', options: '' },
        { title: 'Região Submentoniana', options: '' },
        { title: 'Transfontanelear', options: '' },
    ],
    Muscular: [
        { title: 'Glúteos', options: '' },
        { title: 'Coxa', options: 'Deve incluir esquerdo/direito e botinha' },
        { title: 'Panturrilha', options: 'Deve incluir doppler' },
        { title: 'Pé', options: 'Deve incluir doppler e botinha' },
        { title: 'Perna', options: 'Deve incluir botinha'},
        { title: 'Punho', options: 'Deve incluir doppler'},
        { title: 'Tornozelo', options: 'Deve incluir botinha'},
        { title: 'Tendão de Aquiles', options: ''},
        { title: 'Quadril', options: 'Deve incluir RN'},
        { title: 'Ombro', options: 'Deve incluir doppler'},
        { title: 'Mão', options: 'Deve incluir doppler e botinha'},
        { title: 'Joelho', options: 'Deve incluir doppler'},
        { title: 'Cotovelo', options: 'Deve incluir botinha'},
        { title: 'Braço', options: 'Deve incluir botinha'},
        { title: 'Antebraço', options: 'Deve incluir doppler'},
        { title: 'Calcâneo', options: ''},
        { title: 'Dedo', options: 'Deve incluir polegar esquerdo/direito'},
        { title: 'Fossa Poplítea', options: ''},
        { title: 'Deltóide', options: ''},
        { title: 'Bursas Trocantéricas', options: ''},
        { title: 'Musculatura Abdominal', options: ''},
        { title: 'Terceiro Pododáclito', options: 'Deve incluir esquerdo/direito'},
    ],
    Doppler: [
        { title: 'Ultrassom Doppler', options: 'Avaliação do fluxo sanguíneo em veias e artérias.' },
        { title: 'Doppler Colorido', options: 'Exame que utiliza cores para visualizar o fluxo sanguíneo.' },
    ],
    Superfície: [
        { title: 'Ultrassom Facial', options: 'Tratamento estético para melhorar a pele do rosto.' },
        { title: 'Ultrassom Corporal', options: 'Terapia para aliviar dores e inflamações em áreas específicas.' },
    ],
    Outros: [
        { title: 'Consulta Geral', options: 'Avaliação médica completa com orientações.' },
    ],
};
