// consultations.ts
export const consultations = [
    'Masculino',
    'Feminino',
    'Abdomen',
    'Cabeça e Pescoço',
    'Muscular',
    'Doppler',
    'Superfície',
    'Outros',
];

export const optionsMap = {
    Masculino: [
        { title: 'Axila', options: 'Detalhes aqui' },
        { title: 'Escrotal', options: 'Orientações sobre ultrassom escrotal' },
        { title: 'Mamas', options: 'Exame da mama' },
        { title: 'Pelvis', options: 'Deve incluir pediátrica' },
        { title: 'Prostata', options: 'Avaliação da saúde da próstata.' },
        { title: 'Transretal', options: 'Avaliação da saúde dos rins' },
    ],
    Feminino: [
        { title: 'Axila', options: 'Deve incluir doppler.' },
        { title: 'Diu', options: 'Detalhes aqui' },
        { title: 'Mamas', options: 'Deve incluir doppler.' },
        { title: 'Morfologicas', options: 'Deve incluir gemelar, trigemelar, com doppler e uterinas.' },
        { title: 'Obstetrica', options: 'Deve incluir trigemelar, inicial, com doppler, e todas as combinações' },
        { title: 'Transvarginal', options: 'Deve incluir seriada, pós histerectomia, avaliação cólo, musa IETA FIGO, contagem de folículos e com doppler. ' },
        { title: 'Pelvis', options: 'Deve incluir seriada e com doppler' },
        { title: 'Transsonografia', options: 'Deve incluir morfológica, gemelar e com doppler' },
    ],
    Abdomen: [
        { title: 'Parede', options: '' },
        { title: 'Superior', options: '' },
        { title: 'Total', options: 'Deve incluir pediátrico e novo' },
        { title: 'RimEnxertado', options: 'Deve incluir doppler' },
        { title: 'Hipocondrio', options: 'Deve incluir esquerdo/direito' },
        { title: 'FigadoViaBilares', options: 'Deve incluir doppler de veia porta' },
        { title: 'FID', options: '' },
        { title: 'AparelhoUrinario', options: 'Deve incluir pediátrico e doppler' },
        { title: 'RegiaoSacrococigea', options: '' },
    ],
    'Cabeça e Pescoço': [
        { title: 'Facial', options: 'Deve incluir lateral esquerda/direita'},
        { title: 'Tireoide', options: '' },
        { title: 'Cervical', options: 'Deve incluir tireóide, posterior e com doppler' },
        { title: 'CouroCabeludo', options: '' },
        { title: 'Glandulas', options: 'Deve incluir Salivares, Parótidas, Submandibulares e Submandibulares e Sublinguais'},
        { title: 'LateralPescoco', options: '' },
        { title: 'RegiaoParietal', options: '' },
        { title: 'RegiaoAuricularSubmentoniana', options: 'Deve incluir Periauricular, Retroauricular & Submentoniana' },
        { title: 'Transfontanelear', options: '' },
    ],
    Muscular: [
        { title: 'Gluteos', options: '' },
        { title: 'Coxa', options: 'Deve incluir esquerdo/direito e botinha' },
        { title: 'Panturrilha', options: 'Deve incluir doppler' },
        { title: 'Pe', options: 'Deve incluir doppler e botinha' },
        { title: 'Perna', options: 'Deve incluir botinha'},
        { title: 'Punho', options: 'Deve incluir doppler'},
        { title: 'Tornozelo', options: 'Deve incluir botinha'},
        { title: 'TendaoAquiles', options: ''},
        { title: 'Quadril', options: 'Deve incluir RN'},
        { title: 'Ombro', options: 'Deve incluir doppler'},
        { title: 'Mao', options: 'Deve incluir doppler e botinha'},
        { title: 'Joelho', options: 'Deve incluir doppler'},
        { title: 'Cotovelo', options: 'Deve incluir botinha'},
        { title: 'BracoAntebraco', options: 'Deve incluir Antebraco, doppler e botinha'},
        { title: 'Calcaneo', options: ''},
        { title: 'Dedo', options: 'Deve incluir polegar esquerdo/direito'},
        { title: 'FossaPoplitea', options: ''},
        { title: 'Deltoide', options: ''},
        { title: 'BursasTrocantericas', options: ''},
        { title: 'MusculaturaAbdominal', options: ''},
        { title: 'TerceiroPododaclito', options: 'Deve incluir esquerdo/direito'},
    ],
    Doppler: [
        { title: 'Ultrassom Doppler', options: 'Avaliação do fluxo sanguíneo em veias e artérias.' },
        { title: 'Doppler Colorido', options: 'Exame que utiliza cores para visualizar o fluxo sanguíneo.' },
    ],
    Superfície: [
        { title: 'Ultrassom Facial', options: 'Tratamento estético para melhorar a pele do rosto.' },
        { title: 'Ultrassom Corporal', options: 'Terapia para aliviar dores e inflamações em áreas específicas.' },
    ],
    Outros: [
        { title: 'Consulta Geral', options: 'Avaliação médica completa com orientações.' },
    ],
};
